---
- name: Install httpd
  tags: httpd
  become: true
  package:
    state: present
    name: httpd

- name: Install modules
  tags: httpd
  become: true
  notify: service httpd restart
  with_items: "{{ httpd_extra_modules }}"
  package:
    state: present
    name: "{{ item }}"

- name: Remove default configs
  tags: httpd
  become: true
  notify: service httpd restart
  with_items:
    - autoindex.conf
    - README
    - userdir.conf
    - welcome.conf
  file:
    state: absent
    path: "/etc/httpd/conf.d/{{ item }}"

- name: Deploy httpd.conf
  tags: httpd
  become: true
  notify: service httpd restart
  template:
    src: httpd.conf.j2
    dest: /etc/httpd/conf/httpd.conf

- name: Start and enable httpd
  tags: httpd
  become: true
  service:
    enabled: true
    state: started
    name: httpd
