---

# Install role facts
#   This should be the last tasks in main.yml.
#   Add any other tasks above this one, if applicable.
- name: Include facts management
  tags:
    - httpd
    - facts
    - localfacts
  include: "{{ playbook_dir }}/roles/silpion.lib/tasks/localfacts.yml"
  vars:
    namespace: httpd
